# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c0a1a332af699d0972e31979eacb242d5b09b7f7a41e10397e84cabe1e301b9d372b03647d31382ff88d8f589c305ae940b18928d030679690c85ca9a809c15

test:
  secret_key_base: 37ad3fc62dd5b9e248ab935be6095e53f593f8d29ccf47d4ee8993b26328e1bc359fe8f1b86056864a9cb41c144bc2e17a6ebfb412d71ee5ab7bb679e0a4de86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
