stack_name: testsporerailspaas2-qa
environment: test
paas_environment: test

layers:
  - dns:
      - name: 'testsporerailspaas2.test.paas.vodalabs.com.au'
    instances:
      ami_name: <%=ami_name%>
      env:
        LOG_FILENAME: testsporerailspaas2-qa
